---
server:
  port: ${SERVER_PORT:9001}
logging:
  level:
    org:
      apache:
        coyote:
          http11: WARN
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

database:
  mongo:
    url: ${DATABASE_URL:mongodb://localhost:27017}
    name: ${DATABASE_NAME:sandbox_client}

registry_service:
  url: ${REGISTRY_URL:https://demo4460370.mockable.io/registry/}
  retry:
    max_attempts: ${REGISTRY_RETRY_MAX_ATTEMPTS:3}
    initial_interval_in_millis: ${REGISTRY_RETRY_INTERVAL:1000}
    interval_multiplier: ${REGISTRY_RETRY_INTERVAL_MULTIPLIER:1.0}
  cache:
    expiry_cron_schedule: '0 */5 * * * *'
  timeouts:
    connection_in_seconds: ${REGISTRY_CONNECTION_TIMEOUT:10}
    read_in_seconds: ${REGISTRY_READ_TIMEOUT:10}
    write_in_seconds: ${REGISTRY_WRITE_TIMEOUT:10}
gateway_service:
  retry:
    max_attempts: ${GATEWAY_RETRY_MAX_ATTEMPTS:3}
    initial_interval_in_millis: ${GATEWAY_RETRY_INTERVAL:1000}
    interval_multiplier: ${GATEWAY_RETRY_INTERVAL_MULTIPLIER:1.0}
  cache:
    expiry_cron_schedule: '0 */5 * * * *'
  timeouts:
    connection_in_seconds: ${GATEWAY_CONNECTION_TIMEOUT:10}
    read_in_seconds: ${GATEWAY_READ_TIMEOUT:10}
    write_in_seconds: ${GATEWAY_WRITE_TIMEOUT:10}
bpp_registry_service:
  url: ${BPP_URL:https://demo4460370.mockable.io/bpp_registry/}
bpp_service:
  retry:
    max_attempts: ${BPP_RETRY_MAX_ATTEMPTS:3}
    initial_interval_in_millis: ${BPP_RETRY_INTERVAL:1000}
    interval_multiplier: ${BPP_RETRY_INTERVAL_MULTIPLIER:1.0}
  cache:
    expiry_cron_schedule: '0 */5 * * * *'
  timeouts:
    connection_in_seconds: ${BPP_CONNECTION_TIMEOUT:10}
    read_in_seconds: ${BPP_READ_TIMEOUT:10}
    write_in_seconds: ${BPP_WRITE_TIMEOUT:10}
protocol_service:
  url: ${PROTOCOL_HELPER_URL:http://localhost:9002/}
  retry:
    max_attempts: ${PROTOCOL_HELPER_RETRY_MAX_ATTEMPTS:3}
    initial_interval_in_millis: ${PROTOCOL_HELPER_RETRY_INTERVAL:1000}
    interval_multiplier: ${PROTOCOL_HELPER_RETRY_INTERVAL_MULTIPLIER:1.0}
  timeouts:
    connection_in_seconds: ${PROTOCOL_HELPER_CONNECTION_TIMEOUT:5}
    read_in_seconds: ${PROTOCOL_HELPER_READ_TIMEOUT:5}
    write_in_seconds: ${PROTOCOL_HELPER_WRITE_TIMEOUT:5}

context:
  domain: ${BAP_DOMAIN:nic2004:52110}
  city: ${BAP_CITY_CODE:std:080}
  country: ${BAP_COUNTRY_CODE:IND}
  bap_id: ${BAP_ID:box.beckn.org}
  bap_uri: ${BAP_URL:http://localhost:9002/protocol/v1}
  ttl_seconds: ${BAP_TTL:20}

beckn:
  security.enabled: ${BECKN_SECURITY_ENABLED:false}
security:
  self:
    private_key: ${BAP_PRIVATE_KEY:some-key}
    unique_key_id: ${BAP_KEY_ID:default-key}
  firebase-props:
    enable-strict-server-session: ${FIREBASE_STRICT_SERVER_SESSION:false}
    enable-check-session-revoked: ${FIREBASE_CHECK_SESSION_REVOKED:false}
    enable-logout-everywhere: ${FIREBASE_ENABLE_LOGOUT_EVERYWHERE:false}
    session-expiry-in-days: ${FIREBASE_SESSION_EXPIRY:5}
  allow-credentials: ${BECKN_SECURITY_ALLOW_CREDENTIALS:true}
  allowed-origins:
    - http://localhost:9001
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /public/**
  exposed-headers:
    - X-Xsrf-Token
  protected-actions:
    - /client/v2/initialize_order
    - /client/v2/on_initialize_order
    - /client/v2/confirm_order
    - /client/v2/on_confirm_order
    - /client/v2/get_quote
    - /client/v2/on_get_quote
    - /client/v1/orders
    - /client/v2/on_track
    - /client/v2/track
    - /client/v2/on_order_status
    - /client/v2/order_status
    - /client/v1/delivery_address
    - /client/v2/confirm_order
    - /client/v1/billing_details
    - /client/v1/account_details
    - /client/v2/on_support
    - /client/v2/get_support

management:
  endpoints:
    web:
      exposure:
        include:
          'configprops, env, health, loggers, metrics, mappings, httptrace'
